import type { Metadata } from 'next';
import { Playfair_Display, Roboto_Mono } from 'next/font/google';

import Header from '@/components/Header';

import '@/styles/_global.scss';
import '@/styles/_typography.scss';
import './main.scss';

const playfair_display = Playfair_Display({
  subsets: ['latin', 'vietnamese'],
  variable: '--font-playfair-display',
  display: 'swap',
});

const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto-mono',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${playfair_display.variable} ${roboto_mono.variable} mdl-js`}
    >
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
